# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

# Note: GitHub Actions is now the primary CI system for this project.
# This Travis CI configuration is maintained for compatibility.

osx_image: xcode14.2
language: objective-c
cache: cocoapods
podfile: Example/Podfile

before_install:
  - gem install cocoapods
  - pod install --project-directory=Example

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/RBSFiveStarRating.xcworkspace -scheme RBSFiveStarRating-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - pod lib lint --allow-warnings
